### ISSUE TITLE
missing documentation on commands

### ISSUE THREAD

**Issue by simkoc** [timschubert/abgabesystem#10]
There is no documentation on how to use the commands projects/deadline/plagiates.

Running `abgabesystem projects -c "Test" -d id_rsa`  results in
```
Traceback (most recent call last):
  File "/opt/abgabesystem/bin/abgabesystem", line 60, in <module>
    args.func(gl, args)
  File "/opt/abgabesystem/lib/python3.6/site-packages/abgabesystem/commands.py", line 46, in projects
    setup_projects(gl, course, key)
  File "/opt/abgabesystem/lib/python3.6/site-packages/abgabesystem/projects.py", line 147, in setup_projects
    raise InvalidCourse("No solutions subgroup")
```

When is this subgroup supposed to be created?

**Comment by timschubert** [comment]
There is in-code documentation for these commands. They are to be exclusively used by the CI script. But you should also be able to run them manually. 

This exception no longer is raised anywhere in the code in the current `master` branch. Please try again with the latest `master`. The subgroup should be created either on course creation or, if it does not already exist, as the command you provided is being run.

**Comment by timschubert** [comment]
#4
